### ISSUE TITLE
Level in User info seems to be incorrect

### ISSUE THREAD

**Issue by tanllwyth01** [GeekBeacon/gb-svc-beacon-bot#22] opened 2021-10-28 03:16 UTC
When I ran `!userinfo` it showed the level as 1, when it should be 3 by the number of points. 
![Screenshot_20211027-162339](https://user-images.githubusercontent.com/3087315/139180169-a3f643d1-7fb4-4136-ab13-233b024be87b.png)

**Comment by kankurodev** [comment] 2021-11-24 03:14
Closing this since I'm not sure how to reproduce it. If it happens again let me know @tanllwyth01

**Closed by kankurodev** 2021-11-24 03:14 UTC
